
#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_trec.sh

#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_sst2.sh
#baseline reasonable, #finanl is bad: check the code didn't brak when run

#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_sciie.sh

#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new.sh

#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_chemprot.sh

#bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_scicite.sh


########
########

#change 10 iteration 1 retrive
#No ration

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_all_entropy.sh

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_trec_all_entropy.sh

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_sst2_all_entropy.sh
#baseline reasonable, #finanl is bad: check the code didn't brak when run

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_sst5_all_entropy.sh

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_sciie_all_entropy.sh


bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_chemprot_all_entropy.sh

bash run_pretrain_roberta_including_Preprocess_DomainTask_sentiment_noaspect_HEADandTAIL_pipeline_updateRep_opendomain_new_scicite_all_entropy.sh


